// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
	"time"
)

type Event struct {
	EventID     []byte
	UserID      []byte
	Name        string
	Description sql.NullString
	Location    sql.NullString
	DateTime    time.Time
}

type User struct {
	UserID   []byte
	Email    string
	Password string
}
